const config = {
  REACT_APP_SECRET_ACCESS_KEY:process.env.REACT_APP_SECRET_ACCESS_KEY,

  REACT_APP_SAFETY_PROTOCOL_API:process.env.REACT_APP_SAFETY_PROTOCOL_API,

  REACT_APP_FACT_CHECKER_API:process.env.REACT_APP_FACT_CHECKER_API,

  REACT_APP_BUCKET_NAME:process.env.REACT_APP_BUCKET_NAME,

  REACT_APP_AI_GEN_TEXT_API:process.env.REACT_APP_AI_GEN_TEXT_API,

  REACT_APP_AI_GEN_IMAGE_API:process.env.REACT_APP_AI_GEN_IMAGE_API,
  
  REACT_APP_ACCESS_KEY:process.env.REACT_APP_ACCESS_KEY,

  };
  
  export default config;
  